IberaDelivery/Controllers/NavbarController.cs
using Microsoft.AspNetCore.Mvc;
using IberaDelivery.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using System;
using System.IO;
using System.Threading.Tasks;
using System.Drawing;
using System.Text.Json;
using System.Text.Json.Serialization;


namespace IberaDelivery.Controllers
{
    public class NavbarController : Controller
    {
        private readonly iberiadbContext dataContext;

        public NavbarController(iberiadbContext context)
        {
            dataContext = context;
        }

        [HttpPost]
        public IActionResult Search(IFormCollection form)
        {
            var products = dataContext.Products.ToList();
            ViewBag.Search = form["SearchField"];
            string searchField = form["SearchField"];
            int category = int.Parse(form["Category"]);
            if (searchField != null)
            {
                if (category != 0)
                {
                    products = dataContext.Products.Where(a => a.Name.Contains(searchField) && a.CategoryId.Equals(category)).Include(i => i.Images).Include(c => c.Category).Include(p => p.Provider).ToList();
                }
                else
                {
                    products = dataContext.Products.Where(a => a.Name.Contains(searchField)).Include(i => i.Images).Include(c => c.Category).Include(p => p.Provider).ToList();
                }
                return View(products);
            }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Search(String src, int cat)
        {
            var products = dataContext.Products.ToList();
            ViewBag.Search = src;
            string searchField = src;
            int category = cat;
            if (category != 0)
            {
                products = dataContext.Products.Where(a => a.Name.Contains(searchField) && a.CategoryId.Equals(category)).Include(i => i.Images).Include(c => c.Category).Include(p => p.Provider).ToList();
            }
            else
            {
                products = dataContext.Products.Where(a => a.Name.Contains(searchField)).Include(i => i.Images).Include(c => c.Category).Include(p => p.Provider).ToList();
            }
            if (products.Count == 0)
            {
                var product = dataContext.Products
                .Include(p => p.Images)
                .Include(p => p.Category)
                .Include(p => p.Provider)
                .Include(p => p.Comments);
                return View(product);
            }
            return View(products);
        }
    }
}

IberaDelivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IberaDelivery</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IberaDelivery.styles.css" asp-append-version="true" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home"
                    asp-action="Index">IberiaDelivery</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="contSearch">
                    <partial name="_SearchForm" />
                </div>
                <div class="navbar-collapse-md collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav"></ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-info text-muted">
        <div class="container text-light">
            &copy; 2022 - IberaDelivery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- JavaScript Bundle with Popper -->
    <link href="@Url.Content("~/Content/jquery.rating.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/js/jquery.rating.pack.js")" type="text/javascript"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

IberaDelivery/Views/Shared/_SearchForm.cshtml
@inject iberiadbContext context
@using (Html.BeginForm("Search", "Navbar"))
{
    List<SelectListItem> listItems = new List<SelectListItem>();
    
    List<Category> categories = context.Categories.ToList();
    listItems.Add(new SelectListItem{
            Text = "All departments",
            Value = "0",
            Selected = true
        });
    foreach(Category cat in categories){
        listItems.Add(new SelectListItem{
            Text = cat.Name,
            Value = cat.Id + ""
        });
    }
    <div class="row">
        <div class="col-xl-2 col-lg-2 col-md-12 col-sm-12">
            @Html.DropDownList("Category", listItems, new { @class = "form-control" })
        </div>
        <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12">
            @Html.TextBox("SearchField", null, new { @class = "form-control w-100", @placeholder = "Search product..."})
        </div>
        <div class="col-xl-1 col-lg-1 col-md-12 col-sm-12">
            <input type="submit" value="Search" class="btn btn-light" />
        </div>
    </div>
}