IberaDelivery/Models/CreditCard/CreditCard.cs
using System;
using System.Collections.Generic;

namespace IberaDelivery.Models
{
    public partial class CreditCard
    {
        public CreditCard()
        {
            Orders = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string CardNumber { get; set; } = null!;
        public int UserId { get; set; }
        public string Cardholder { get; set; } = null!;

        public virtual User User { get; set; } = null!;
        public virtual ICollection<Order> Orders { get; set; }
    }
}

IberaDelivery/Models/CreditCard/CreditCardEditForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IberaDelivery.Models
{
    public partial class CreditCardEditForm{

        public int Id {get; set; }
        [Required]
        public string CardNumber { get; set; } = null!;
        [Required]
        public string Cardholder { get; set; } = null!;
    }
}

IberaDelivery/Models/CreditCard/CreditCardForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IberaDelivery.Models
{
    public partial class CreditCardForm
    {

        [Required]
        public string CardNumber { get; set; } = null!;
        [Required]
        public string Cardholder { get; set; } = null!;
    }
}

IberaDelivery/Controllers/CreditCardController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IberaDelivery.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace IberaDelivery.Controllers
{
    public class CreditCardController : Controller
    {
        private readonly iberiadbContext dataContext;

        public CreditCardController(iberiadbContext context)
        {
            dataContext = context;
        }

        // GET: CreditCard
        public async Task<IActionResult> Index()
        {
            var credCard = dataContext.CreditCards
            .AsNoTracking();
            return View(await credCard.ToListAsync());

        }

        // GET: CreditCard/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CreditCard/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreditCard creditCard)
        {

            if (ModelState.IsValid)
            {
                dataContext.Add(creditCard);
                dataContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                //ViewBag.missatge = autor.validarAutor().Missatge;
                return View();
            }
        }

        // GET: CreditCard/Delete/id
        public IActionResult Delete(int? id)
        {
            //if (HttpContext.Session.GetString("userName") != null)
            //{
            if (id == null)
            {
                return NotFound();
            }

            var creditCard = dataContext.CreditCards
                .FirstOrDefault(a => a.Id == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }
        /*
        else
        {
            return Redirect("/");
        }
        */


        // POST: CreditCard/Delete/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var creditCard = dataContext.CreditCards.Find(id);
            if (creditCard != null)
            {
                dataContext.CreditCards.Remove(creditCard);
                dataContext.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            //if (HttpContext.Session.GetString("userName") != null)
            //{
            if (id == null)
            {
                return NotFound();
            }
            var creditCard = dataContext.CreditCards
                .FirstOrDefault(a => a.Id == id);
            //.Find(id);
            if (creditCard == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            return View(creditCard);
            //}
        }

        // POST: CreditCard/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CreditCard creditCard)
        {
            if (ModelState.IsValid)
            {
                var original = dataContext.CreditCards.Where(s => s.Id == creditCard.Id).FirstOrDefault();
                dataContext.Entry(original).CurrentValues.SetValues(creditCard);
                dataContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                //ViewBag.missatge = category.validarCategory().msg;
                return View();
            }
        }


        public IActionResult Details(int? id)
        {
                if (id == null)
                {
                    return NotFound();
                }
                var creditCard = dataContext.CreditCards
                    .FirstOrDefault(a => a.Id == id);
                if (creditCard == null)
                {
                    return NotFound();
                }
                return View(creditCard);
        }
    }
}

IberaDelivery/Controllers/CreditcardController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IberaDelivery.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace IberaDelivery.Controllers
{
    public class CreditCardController : Controller
    {
        private readonly iberiadbContext dataContext;

        public CreditCardController(iberiadbContext context)
        {
            dataContext = context;
        }

        // GET: CreditCard
        public async Task<IActionResult> Index()
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }

                int id = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id;

                var credCards = dataContext.CreditCards
                .Where(a => a.UserId == id);
                return View(credCards.ToList());
            }
            catch (Exception e)
            {
                return RedirectToAction("Error500", "Home");
            }
        }

        // GET: CreditCard/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: CreditCard/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreditCardForm creditCardForm)
        {

            if (ModelState.IsValid)
            {
                CreditCard creditCard = new CreditCard();

                creditCard.UserId = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id;
                creditCard.Cardholder = creditCardForm.Cardholder;
                creditCard.CardNumber = creditCardForm.CardNumber;

                dataContext.CreditCards.Add(creditCard);
                dataContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        // GET: CreditCard/Delete/5
        public IActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var creditCard = dataContext.CreditCards
                    .FirstOrDefault(a => a.Id == id);
                var userId = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id;
                if (creditCard == null || creditCard.UserId != userId)
                {
                    return RedirectToAction("Error500", "Home");
                }
                return View(creditCard);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error500", "Home");
            }
        }


        // POST: CreditCard/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                var creditCard = dataContext.CreditCards.Find(id);
                if (creditCard != null)
                {
                    var Orders = dataContext.Orders.Where(a => a.CreditCardId == creditCard.Id).ToList();
                    foreach (var order in Orders)
                    {
                        order.CreditCardId = null;
                        dataContext.Update(order);
                    }
                    dataContext.CreditCards.Remove(creditCard);
                    dataContext.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction("Error500", "Home");
            }
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var creditCard = dataContext.CreditCards
                .FirstOrDefault(a => a.Id == id);
            CreditCardEditForm CreditCardEditForm = new CreditCardEditForm();
            CreditCardEditForm.Id = creditCard.Id;
            CreditCardEditForm.Cardholder = creditCard.Cardholder;
            CreditCardEditForm.CardNumber = creditCard.CardNumber;
            if (creditCard == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            if (checkUserIsAdmin() || creditCard.UserId == JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id)
            {
                return View(CreditCardEditForm);
            }
            else
            {
                return RedirectToAction("Error500", "Home");
            }
        }

        // POST: CreditCard/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CreditCardEditForm creditCard)
        {
            if (ModelState.IsValid)
            {
                var original = dataContext.CreditCards.Where(s => s.Id == creditCard.Id).FirstOrDefault();
                original.Cardholder = creditCard.Cardholder;
                original.CardNumber = creditCard.CardNumber;
                if (checkUserIsAdmin() || original.UserId == JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id)
                {
                    dataContext.Update(original);
                    dataContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Error500", "Home");
                }
            }
            else
            {
                return View();
            }
        }


        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (checkUserIsClient() || checkUserIsProveidor())
            {
                var creditCard = dataContext.CreditCards
                                .FirstOrDefault(a => a.Id == id);
                if (creditCard == null || creditCard.UserId != JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id)
                {
                    return NotFound();
                }
                return View(creditCard);
            }
            return NotFound();

        }
        public bool checkUserExists()
        {
            // If (user == null) return false
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
            {
                return false;
            }
            // else return true
            return true;
        }
        public bool checkUserIsClient()
        {
            // If (rol == 3) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 3)
            {
                return true;
            }
            // Else return false;
            return false;
        }
        public bool checkUserIsProveidor()
        {
            // If (rol == 2) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 2)
            {
                return true;
            }
            // Else return false;
            return false;
        }
        public bool checkUserIsAdmin()
        {
            // If (rol == 1) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 1)
            {
                return true;
            }
            // Else return false;
            return false;
        }
    }
}

IberaDelivery/Views/CreditCard/Create.cshtml
@model IberaDelivery.Models.CreditCardForm
@inject IHttpContextAccessor HttpContextAccessor
@using System.Text.Json
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Credit Card Information</h4>
<hr />
<div class="row">
    @using (Html.BeginForm("Create", "CreditCard"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="col-lg-12">@ViewBag.Message</div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.CardNumber)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.CardNumber, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Cardholder)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Cardholder, new { @class = "form-control" })</div>
            </div><br />
        </div>
        <div class="col-md-6">
            <input type="submit" value="Create" class="btn btn-info" />
        </div>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

IberaDelivery/Views/CreditCard/Delete.cshtml
@model IberaDelivery.Models.CreditCard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure of deleting this Credit Card:</h3>
<div>
    <h4>Credit card</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cardholder)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cardholder)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete"  class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IberaDelivery/Views/CreditCard/Edit.cshtml
@model IberaDelivery.Models.CreditCardEditForm
@inject IHttpContextAccessor HttpContextAccessor
@using System.Text.Json
@{
    ViewData["Title"] = "Edit";

}

<h1>Edit</h1>

<h4>Credit Card Information</h4>
<hr />
<div class="row">
    @using (Html.BeginForm("Edit", "CreditCard"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="col-lg-12">@ViewBag.Message</div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.CardNumber)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.CardNumber, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Cardholder)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Cardholder, new { @class = "form-control" })</div>
            </div><br />
        </div>
        <div class="col-md-6">
            <input type="submit" value="Edit" class="btn btn-info" />
        </div>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

IberaDelivery/Views/CreditCard/Index.cshtml
@model IEnumerable<IberaDelivery.Models.CreditCard>
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Addresses";

}

<h2>Credit Card Information</h2>

<a asp-action="Create" class="btn btn-info">New Credit Card</a>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cardholder)
            </th>
            <th colspan="2">
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cardholder)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>

            </tr>
        }
    </tbody>
</table>