IberaDelivery/Models/ShipmentInfo/Shipment.cs
using System;
using System.Collections.Generic;

namespace IberaDelivery.Models
{
    public partial class Shipment
    {
        public Shipment()
        {
            Orders = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string Address { get; set; } = null!;
        public string Country { get; set; } = null!;
        public string City { get; set; } = null!;
        public string PostalCode { get; set; } = null!;
        public int UserId { get; set; }

        public virtual User User { get; set; } = null!;
        public virtual ICollection<Order> Orders { get; set; }
    }
}

IberaDelivery/Models/ShipmentInfo/ShipmentForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IberaDelivery.Models
{
    public partial class ShipmentForm{

        [Required]
        public string Address { get; set; } = null!;
        [Required]
        public string Country { get; set; } = null!;
        [Required]
        public string City { get; set; } = null!;
        [Required]
        public string PostalCode { get; set; } = null!;
    }
}

IberaDelivery/Controllers/ShipmentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IberaDelivery.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace IberaDelivery.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly iberiadbContext dataContext;

        public ShipmentController(iberiadbContext context)
        {
            dataContext = context;
        }
        public IActionResult Index()
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }

                int id = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id;

                var shipment = dataContext.Shipments
                .Where(a => a.UserId == id);
                return View(shipment.ToList());
            }
            catch (Exception e)
            {
                return RedirectToAction("Error500", "Home");
            }
        }
        public IActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShipmentForm shipmentInfo)
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }
                User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user"));

                if (ModelState.IsValid)
                {
                    Shipment shipment = new Shipment();
                    shipment.Address = shipmentInfo.Address;
                    shipment.Country = shipmentInfo.Country;
                    shipment.City = shipmentInfo.City;
                    shipment.PostalCode = shipmentInfo.PostalCode;
                    shipment.UserId = user.Id;
                    dataContext.Shipments.Add(shipment);
                    dataContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {

                return RedirectToAction("Error500", "Home");
            }

        }
        // GET: Shipment/Delete/5
        public IActionResult Delete(int? id)
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }
                if (id == null)
                {
                    return NotFound();
                }

                var shipmentInfo = dataContext.Shipments
                    .FirstOrDefault(a => a.Id == id);
                if (shipmentInfo == null)
                {
                    return NotFound();
                }

                return View(shipmentInfo);
            }
            catch (Exception e)
            {

                return RedirectToAction("Error500", "Home");
            }

        }
        // POST: Shipment/Delete/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                var userId = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Id;
                var shipmentInfo = dataContext.Shipments.Find(id);
                if (shipmentInfo != null)
                {
                    if (shipmentInfo.UserId == userId)
                    {
                        var Orders = dataContext.Orders.Where(a => a.ShipmentId == shipmentInfo.Id).ToList();
                        foreach (var order in Orders)
                        {
                            order.ShipmentId = null;
                            dataContext.Update(order);
                        }
                        dataContext.Shipments.Remove(shipmentInfo);
                        dataContext.SaveChanges();
                    }
                    else
                    {
                        return RedirectToAction("Error500", "Home");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction("Error500", "Home");
            }

        }
        public IActionResult Edit(int? id)
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }
                if (id == null)
                {
                    return NotFound();
                }
                var shipmentInfo = dataContext.Shipments
                    .FirstOrDefault(a => a.Id == id);
                //.Find(id);
                if (shipmentInfo == null)
                {
                    return NotFound();
                }

                ShipmentEditForm form = new ShipmentEditForm();
                form.Address = shipmentInfo.Address;
                form.City = shipmentInfo.City;
                form.Country = shipmentInfo.Country;
                form.PostalCode = shipmentInfo.PostalCode;
                form.Id = shipmentInfo.Id;
                ViewBag.Id = id;
                return View(form);
            }
            catch (Exception e)
            {

                return RedirectToAction("Error500", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ShipmentEditForm shipmentInfo)
        {
            try
            {
                if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
                {
                    return RedirectToAction("Index", "Home");
                }
                if (ModelState.IsValid)
                {
                    Shipment regShipmentInfo = dataContext.Shipments.Where(s => s.Id == shipmentInfo.Id).FirstOrDefault();
                    regShipmentInfo.Address = shipmentInfo.Address;
                    regShipmentInfo.City = shipmentInfo.City;
                    regShipmentInfo.Country = shipmentInfo.Country;
                    regShipmentInfo.PostalCode = shipmentInfo.PostalCode;
                    dataContext.Shipments.Update(regShipmentInfo);
                    dataContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    //ViewBag.missatge = category.validarCategory().msg;
                    return View();
                }
            }
            catch (Exception e)
            {

                return RedirectToAction("Error500", "Home");
            }

        }
        public bool checkUserExists()
        {
            // If (user == null) return false
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("user")))
            {
                return false;
            }
            // else return true
            return true;
        }
        public bool checkUserIsClient()
        {
            // If (rol == 3) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 3)
            {
                return true;
            }
            // Else return false;
            return false;
        }
        public bool checkUserIsProveidor()
        {
            // If (rol == 2) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 2)
            {
                return true;
            }
            // Else return false;
            return false;
        }
        public bool checkUserIsAdmin()
        {
            // If (rol == 1) return true
            if (JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("user")).Rol == 1)
            {
                return true;
            }
            // Else return false;
            return false;
        }
    }
}

IberaDelivery/Views/Shipment/Create.cshtml
@model IberaDelivery.Models.ShipmentForm
@inject IHttpContextAccessor HttpContextAccessor
@using System.Text.Json
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shipment Information</h4>
<hr />
<div class="row">
    @using (Html.BeginForm("Create", "Shipment"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="col-lg-12">@ViewBag.Message</div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Address)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Address, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Country)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Country, new { @class = "form-control" })</div>
            </div><br />
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.City)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.City, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">Postal Code </div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.PostalCode, new { @class = "form-control" })</div>
            </div><br />
            <input type="submit" value="Create" class="btn btn-info" />
        </div>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

IberaDelivery/Views/Shipment/Delete.cshtml
@model IberaDelivery.Models.Shipment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Do you want to delete this shipment address?</h3>
<div>
    <h4>Shipment address:</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IberaDelivery/Views/Shipment/Edit.cshtml
@model IberaDelivery.Models.ShipmentEditForm
@inject IHttpContextAccessor HttpContextAccessor
@using System.Text.Json
@{
    ViewData["Title"] = "Edit";

}

<h1>Edit</h1>

<h4>Shipment Information</h4>
<hr />
<div class="row">
    @using (Html.BeginForm("Edit", "Shipment"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="col-lg-12">@ViewBag.Message</div>
        <div class="col-md-6">
            <div class="col-lg-10">@Html.TextBoxFor(a => a.Id, new { @class = "form-control", type = "Hidden" })</div>
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Address)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Address, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.Country)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.Country, new { @class = "form-control" })</div>
            </div><br />
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-lg-2">@Html.LabelFor(a => a.City)</div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.City, new { @class = "form-control" })</div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">Postal Code </div>
                <div class="col-lg-10">@Html.TextBoxFor(a => a.PostalCode, new { @class = "form-control" })</div>
            </div><br />
            <input type="submit" value="Edit" class="btn btn-info" />
        </div>
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

IberaDelivery/Views/Shipment/Index.cshtml
@model IEnumerable<IberaDelivery.Models.Shipment>
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Addresses";

}

<h2>Shipment Information</h2>

<a asp-action="Create" class="btn btn-info">New Shipment Information +</a>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th>
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostalCode)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>

            </tr>
        }
    </tbody>
</table>